// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var BsCallback = require("bs-callback/lib/js/src/bsCallback.js");
var YoutubeDl$BsYoutubeDl = require("../src/YoutubeDl.js");

BsCallback.finish(/* None */0, BsCallback.$great$great(YoutubeDl$BsYoutubeDl.metadata("https://youtu.be/uRr708wY7Nk"), (function (vid) {
            console.log(vid);
            return (function (param) {
                return BsCallback.$$return(/* () */0, param);
              });
          })));

/*  Not a pure module */
